alter table TSADV_PERSON_COIN add constraint FK_TSADV_PERSON_COIN_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_COIN_PERSON_GROUP on TSADV_PERSON_COIN (PERSON_GROUP_ID);
