alter table TSADV_GOODS_WAREHOUSE add constraint FK_TSADV_GOODS_WAREHOUSE_GOOD foreign key (GOOD_ID) references TSADV_GOODS(ID);
create index IDX_TSADV_GOODS_WAREHOUSE_GOOD on TSADV_GOODS_WAREHOUSE (GOOD_ID);
