alter table TSADV_RECOGNITION add constraint FK_TSADV_RECOGNITION_RECEIVER foreign key (RECEIVER_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_RECOGNITION_RECEIVER on TSADV_RECOGNITION (RECEIVER_ID);
