alter table TSADV_COMPETENCE add constraint FK_TSADV_COMPETENCE_COMPETECE_TYPE foreign key (COMPETECE_TYPE_ID) references TSADV_DIC_COMPETENCE_TYPE(ID);
create index IDX_TSADV_COMPETENCE_COMPETECE_TYPE on TSADV_COMPETENCE (COMPETECE_TYPE_ID);
