alter table TSADV_RECOGNITION_LIKE add constraint FK_TSADV_RECOGNITION_LIKE_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_RECOGNITION_LIKE add constraint FK_TSADV_RECOGNITION_LIKE_RECOGNITION foreign key (RECOGNITION_ID) references TSADV_RECOGNITION(ID);
create index IDX_TSADV_RECOGNITION_LIKE_PERSON_GROUP on TSADV_RECOGNITION_LIKE (PERSON_GROUP_ID);
create index IDX_TSADV_RECOGNITION_LIKE_RECOGNITION on TSADV_RECOGNITION_LIKE (RECOGNITION_ID);
