alter table TSADV_PERSON_AWARD add constraint FK_TSADV_PERSON_AWARD_TYPE foreign key (TYPE_ID) references TSADV_DIC_AWARD_TYPE(ID);
alter table TSADV_PERSON_AWARD add constraint FK_TSADV_PERSON_AWARD_AUTHOR foreign key (AUTHOR_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_PERSON_AWARD add constraint FK_TSADV_PERSON_AWARD_RECEIVER foreign key (RECEIVER_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_AWARD_TYPE on TSADV_PERSON_AWARD (TYPE_ID);
create index IDX_TSADV_PERSON_AWARD_AUTHOR on TSADV_PERSON_AWARD (AUTHOR_ID);
create index IDX_TSADV_PERSON_AWARD_RECEIVER on TSADV_PERSON_AWARD (RECEIVER_ID);
