alter table TSADV_RETIREMENT add constraint FK_TSADV_RETIREMENT_RETIREMENT_TYPE foreign key (RETIREMENT_TYPE_ID) references TSADV_DIC_RETIREMENT_TYPE(ID);
alter table TSADV_RETIREMENT add constraint FK_TSADV_RETIREMENT_PERSON_GROUP_EXT foreign key (PERSON_GROUP_EXT_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_RETIREMENT_RETIREMENT_TYPE on TSADV_RETIREMENT (RETIREMENT_TYPE_ID);
create index IDX_TSADV_RETIREMENT_PERSON_GROUP_EXT on TSADV_RETIREMENT (PERSON_GROUP_EXT_ID);
