alter table TSADV_PERSON_ACTION add constraint FK_TSADV_PERSON_ACTION_RECEIVER foreign key (RECEIVER_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_ACTION_RECEIVER on TSADV_PERSON_ACTION (RECEIVER_ID);
