alter table TSADV_DISABILITY add constraint FK_TSADV_DISABILITY_DISABILITY_TYPE foreign key (DISABILITY_TYPE_ID) references TSADV_DIC_DISABILITY_TYPE(ID);
alter table TSADV_DISABILITY add constraint FK_TSADV_DISABILITY_DURATION foreign key (DURATION_ID) references TSADV_DIC_DURATION(ID);
alter table TSADV_DISABILITY add constraint FK_TSADV_DISABILITY_PERSON_GROUP_EXT foreign key (PERSON_GROUP_EXT_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_DISABILITY_DISABILITY_TYPE on TSADV_DISABILITY (DISABILITY_TYPE_ID);
create index IDX_TSADV_DISABILITY_DURATION on TSADV_DISABILITY (DURATION_ID);
create index IDX_TSADV_DISABILITY_PERSON_GROUP_EXT on TSADV_DISABILITY (PERSON_GROUP_EXT_ID);
