alter table TSADV_PERSON_AWARD add constraint FK_TSADV_PERSON_AWARD_TYPE foreign key (TYPE_ID) references TSADV_DIC_PERSON_AWARD_TYPE(ID);
create index IDX_TSADV_PERSON_AWARD_TYPE on TSADV_PERSON_AWARD (TYPE_ID);
