alter table TSADV_BUSINESS_TRIP_LINES add constraint FK_TSADV_BUSINESS_TRIP_LINES_CITY_FROM foreign key (CITY_FROM_ID) references BASE_DIC_CITY(ID);
create index IDX_TSADV_BUSINESS_TRIP_LINES_CITY_FROM on TSADV_BUSINESS_TRIP_LINES (CITY_FROM_ID);
