alter table TSADV_BUSINESS_TRIP_LINES add constraint FK_TSADV_BUSINESS_TRIP_LINES_CITY_TO foreign key (CITY_TO_ID) references BASE_DIC_CITY(ID);
create index IDX_TSADV_BUSINESS_TRIP_LINES_CITY_TO on TSADV_BUSINESS_TRIP_LINES (CITY_TO_ID);
