alter table TSADV_PERSON_ACTION add constraint FK_TSADV_PERSON_ACTION_AUTHOR foreign key (AUTHOR_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_ACTION_AUTHOR on TSADV_PERSON_ACTION (AUTHOR_ID);
