alter table TSADV_MEDAL_CONDITION add constraint FK_TSADV_MEDAL_CONDITION_MEDAL foreign key (MEDAL_ID) references TSADV_MEDAL(ID);
alter table TSADV_MEDAL_CONDITION add constraint FK_TSADV_MEDAL_CONDITION_QUALITY foreign key (QUALITY_ID) references TSADV_DIC_QUALITY(ID);
alter table TSADV_MEDAL_CONDITION add constraint FK_TSADV_MEDAL_CONDITION_CHILD_MEDAL foreign key (CHILD_MEDAL_ID) references TSADV_MEDAL(ID);
create index IDX_TSADV_MEDAL_CONDITION_MEDAL on TSADV_MEDAL_CONDITION (MEDAL_ID);
create index IDX_TSADV_MEDAL_CONDITION_QUALITY on TSADV_MEDAL_CONDITION (QUALITY_ID);
create index IDX_TSADV_MEDAL_CONDITION_CHILD_MEDAL on TSADV_MEDAL_CONDITION (CHILD_MEDAL_ID);
