alter table TSADV_RECOGNITION add constraint FK_TSADV_RECOGNITION_AUTHOR foreign key (AUTHOR_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_RECOGNITION_AUTHOR on TSADV_RECOGNITION (AUTHOR_ID);
