alter table TSADV_BUSINESS_TRIP add constraint FK_TSADV_BUSINESS_TRIP_ORDER foreign key (ORDER_ID) references TSADV_ORDER(ID);
create index IDX_TSADV_BUSINESS_TRIP_ORDER on TSADV_BUSINESS_TRIP (ORDER_ID);
