alter table TSADV_PERSON_LEARNING_CONTRACT drop column LEARNING_COST__U33042 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column BUSINESS_TRIP_COST__U51887 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column PER_DIEM_COST__U76349 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column LIVING_COST__U26276 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column LEARNING_CENTER__U80936 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column SPECIALIZATION__U92027 cascade ;
alter table TSADV_PERSON_LEARNING_CONTRACT drop column REASON__U05476 cascade ;
