alter table TSADV_INTERNSHIP add constraint FK_TSADV_INTERNSHIP_TRAINEE foreign key (TRAINEE_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_INTERNSHIP add constraint FK_TSADV_INTERNSHIP_INTERNSHIP_TYPE foreign key (INTERNSHIP_TYPE_ID) references TSADV_INTERNSHIP_TYPE(ID);
alter table TSADV_INTERNSHIP add constraint FK_TSADV_INTERNSHIP_MAIN_MENTOR foreign key (MAIN_MENTOR_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_INTERNSHIP_TRAINEE on TSADV_INTERNSHIP (TRAINEE_ID);
create index IDX_TSADV_INTERNSHIP_INTERNSHIP_TYPE on TSADV_INTERNSHIP (INTERNSHIP_TYPE_ID);
create index IDX_TSADV_INTERNSHIP_MAIN_MENTOR on TSADV_INTERNSHIP (MAIN_MENTOR_ID);
