alter table TSADV_INTERNSHIP add constraint FK_TSADV_INTERNSHIP_INTERNSHIP_TYPE foreign key (INTERNSHIP_TYPE_ID) references TSADV_DIC_INTERNSHIP_TYPE(ID);
create index IDX_TSADV_INTERNSHIP_INTERNSHIP_TYPE on TSADV_INTERNSHIP (INTERNSHIP_TYPE_ID);
