alter table TSADV_GOODS_CART add constraint FK_TSADV_GOODS_CART_GOODS foreign key (GOODS_ID) references TSADV_GOODS(ID);
alter table TSADV_GOODS_CART add constraint FK_TSADV_GOODS_CART_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_GOODS_CART_GOODS on TSADV_GOODS_CART (GOODS_ID);
create index IDX_TSADV_GOODS_CART_PERSON_GROUP on TSADV_GOODS_CART (PERSON_GROUP_ID);
