alter table TSADV_SUR_CHARGE add constraint FK_TSADV_SUR_CHARGE_CURRENCY foreign key (CURRENCY_ID) references BASE_DIC_CURRENCY(ID);
create index IDX_TSADV_SUR_CHARGE_CURRENCY on TSADV_SUR_CHARGE (CURRENCY_ID);
