alter table TSADV_PERSON_AWARD add constraint FK_TSADV_PERSON_AWARD_AWARD_PROGRAM foreign key (AWARD_PROGRAM_ID) references TSADV_AWARD_PROGRAM(ID);
create index IDX_TSADV_PERSON_AWARD_AWARD_PROGRAM on TSADV_PERSON_AWARD (AWARD_PROGRAM_ID);
