alter table TSADV_PERSON_MEDAL add constraint FK_TSADV_PERSON_MEDAL_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_PERSON_MEDAL add constraint FK_TSADV_PERSON_MEDAL_MEDAL foreign key (MEDAL_ID) references TSADV_MEDAL(ID);
create index IDX_TSADV_PERSON_MEDAL_PERSON_GROUP on TSADV_PERSON_MEDAL (PERSON_GROUP_ID);
create index IDX_TSADV_PERSON_MEDAL_MEDAL on TSADV_PERSON_MEDAL (MEDAL_ID);
