alter table TSADV_BUSINESS_TRIP add constraint FK_TSADV_BUSINESS_TRIP_PARENT_ORDER foreign key (PARENT_ORDER_ID) references TSADV_BUSINESS_TRIP(ID);
create index IDX_TSADV_BUSINESS_TRIP_PARENT_ORDER on TSADV_BUSINESS_TRIP (PARENT_ORDER_ID);
