alter table TSADV_ATTESTATION add constraint FK_TSADV_ATTESTATION_JOB_GROUP foreign key (JOB_GROUP_ID) references TSADV_JOB_GROUP(ID);
create index IDX_TSADV_ATTESTATION_JOB_GROUP on TSADV_ATTESTATION (JOB_GROUP_ID);
