alter table TSADV_PERSON_PREFERENCE add column DESCRIPTION_EN varchar(2000) ^
update TSADV_PERSON_PREFERENCE set DESCRIPTION_EN = DESCRIPTION where DESCRIPTION_EN is null ;
alter table TSADV_PERSON_PREFERENCE alter column DESCRIPTION_EN set not null ;
alter table TSADV_PERSON_PREFERENCE add column DESCRIPTION_RU varchar(2000) ^
update TSADV_PERSON_PREFERENCE set DESCRIPTION_RU = DESCRIPTION where DESCRIPTION_RU is null ;
alter table TSADV_PERSON_PREFERENCE alter column DESCRIPTION_RU set not null ;
