alter table TSADV_ATTESTATION add constraint FK_TSADV_ATTESTATION_PERSON_GROUP_EXT foreign key (PERSON_GROUP_EXT_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_ATTESTATION_PERSON_GROUP_EXT on TSADV_ATTESTATION (PERSON_GROUP_EXT_ID);
