-- alter table TSADV_JOB_PROTECTION_EQUIPMENT add column PERSONAL_PROTECTION_EQUIPMENT_ID uuid ^
-- update TSADV_JOB_PROTECTION_EQUIPMENT set PERSONAL_PROTECTION_EQUIPMENT_ID = <default_value> ;
-- alter table TSADV_JOB_PROTECTION_EQUIPMENT alter column PERSONAL_PROTECTION_EQUIPMENT_ID set not null ;
alter table TSADV_JOB_PROTECTION_EQUIPMENT add column PERSONAL_PROTECTION_EQUIPMENT_ID uuid not null ;
