alter table TSADV_ATTESTATION_PARTICIPANT add column INTERVIEW_RESULT_ID uuid ;
alter table TSADV_ATTESTATION_PARTICIPANT add column COMMISSION_RECOMENDATION varchar(255) ;
alter table TSADV_ATTESTATION_PARTICIPANT add column NOT_APPEARED BOOLEAN DEFAULT FALSE ;
alter table TSADV_ATTESTATION_PARTICIPANT add column NOT_APPEARED_REASON varchar(255) ;
