alter table TSADV_COURSE_SECTION_ATTEMPT add constraint FK_TSADV_COURSE_SECTION_ATTEMPT_TEST foreign key (TEST_ID) references TSADV_TEST(ID);
create index IDX_TSADV_COURSE_SECTION_ATTEMPT_TEST on TSADV_COURSE_SECTION_ATTEMPT (TEST_ID);
