alter table TSADV_ATTESTATION add constraint FK_TSADV_ATTESTATION_POSITION_GROUP foreign key (POSITION_GROUP_ID) references BASE_POSITION_GROUP(ID);
create index IDX_TSADV_ATTESTATION_POSITION_GROUP on TSADV_ATTESTATION (POSITION_GROUP_ID);
