alter table TSADV_ATTESTATION_JOB add constraint FK_TSADV_ATTESTATION_JOB_ATTESTATION foreign key (ATTESTATION_ID) references TSADV_ATTESTATION(ID);
alter table TSADV_ATTESTATION_JOB add constraint FK_TSADV_ATTESTATION_JOB_JOB_GROUP foreign key (JOB_GROUP_ID) references TSADV_JOB_GROUP(ID);
create index IDX_TSADV_ATTESTATION_JOB_ATTESTATION on TSADV_ATTESTATION_JOB (ATTESTATION_ID);
create index IDX_TSADV_ATTESTATION_JOB_JOB_GROUP on TSADV_ATTESTATION_JOB (JOB_GROUP_ID);
