alter table TSADV_BUDGET_HEADER_HISTORY add column BUDGET_HEADER_STATUS varchar(50) ^
update TSADV_BUDGET_HEADER_HISTORY set BUDGET_HEADER_STATUS = 'DRAFT' where BUDGET_HEADER_STATUS is null ;
alter table TSADV_BUDGET_HEADER_HISTORY alter column BUDGET_HEADER_STATUS set not null ;
