alter table TSADV_GOODS_RECEIPT add constraint FK_TSADV_GOODS_RECEIPT_GOODS foreign key (GOODS_ID) references TSADV_GOODS(ID);
create index IDX_TSADV_GOODS_RECEIPT_GOODS on TSADV_GOODS_RECEIPT (GOODS_ID);
