alter table TSADV_INTERNSHIP add constraint FK_TSADV_INTERNSHIP_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_INTERNSHIP_PERSON_GROUP on TSADV_INTERNSHIP (PERSON_GROUP_ID);
