alter table TSADV_BUDGET_REQUEST add constraint FK_TSADV_BUDGET_REQUEST_BUDGET_ITEM foreign key (BUDGET_ITEM_ID) references TSADV_DIC_BUDGET_ITEM(ID);
create index IDX_TSADV_BUDGET_REQUEST_BUDGET_ITEM on TSADV_BUDGET_REQUEST (BUDGET_ITEM_ID);
