alter table TSADV_GOODS_ISSUE add constraint FK_TSADV_GOODS_ISSUE_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_GOODS_ISSUE_PERSON_GROUP on TSADV_GOODS_ISSUE (PERSON_GROUP_ID);
