alter table TSADV_BANNER add constraint FK_TSADV_BANNER_IMAGE_LANG1 foreign key (IMAGE_LANG1_ID) references SYS_FILE(ID);
alter table TSADV_BANNER add constraint FK_TSADV_BANNER_IMAGE_LANG2 foreign key (IMAGE_LANG2_ID) references SYS_FILE(ID);
alter table TSADV_BANNER add constraint FK_TSADV_BANNER_IMAGE_LANG3 foreign key (IMAGE_LANG3_ID) references SYS_FILE(ID);
create index IDX_TSADV_BANNER_IMAGE_LANG1 on TSADV_BANNER (IMAGE_LANG1_ID);
create index IDX_TSADV_BANNER_IMAGE_LANG2 on TSADV_BANNER (IMAGE_LANG2_ID);
create index IDX_TSADV_BANNER_IMAGE_LANG3 on TSADV_BANNER (IMAGE_LANG3_ID);
