alter table TSADV_SELECTED_PERSON_AWARD add column DESCRIPTION_LANG_VALUE1 text ;
alter table TSADV_SELECTED_PERSON_AWARD add column DESCRIPTION_LANG_VALUE2 text ;
alter table TSADV_SELECTED_PERSON_AWARD add column DESCRIPTION_LANG_VALUE3 text ;
alter table TSADV_SELECTED_PERSON_AWARD add column DESCRIPTION_LANG_VALUE4 text ;
alter table TSADV_SELECTED_PERSON_AWARD add column DESCRIPTION_LANG_VALUE5 text ;
