alter table TSADV_COURSE_TRAINER add constraint FK_TSADV_COURSE_TRAINER_TRAINER foreign key (TRAINER_ID) references TSADV_TRAINER(ID);
alter table TSADV_COURSE_TRAINER add constraint FK_TSADV_COURSE_TRAINER_COURSE foreign key (COURSE_ID) references TSADV_COURSE(ID);
create index IDX_TSADV_COURSE_TRAINER_TRAINER on TSADV_COURSE_TRAINER (TRAINER_ID);
create index IDX_TSADV_COURSE_TRAINER_COURSE on TSADV_COURSE_TRAINER (COURSE_ID);
