alter table BASE_POSITION add constraint FK_BASE_POSITION_EMPLOYEE_CATEGORY foreign key (EMPLOYEE_CATEGORY_ID) references TSADV_DIC_EMPLOYEE_CATEGORY(ID);
create index IDX_BASE_POSITION_EMPLOYEE_CATEGORY on BASE_POSITION (EMPLOYEE_CATEGORY_ID);
