alter table TSADV_GOODS_ORDER add constraint FK_TSADV_GOODS_ORDER_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_GOODS_ORDER_PERSON_GROUP on TSADV_GOODS_ORDER (PERSON_GROUP_ID);
