alter table TSADV_GOODS_ORDER_DETAIL add constraint FK_TSADV_GOODS_ORDER_DETAIL_GOODS foreign key (GOODS_ID) references TSADV_GOODS(ID);
alter table TSADV_GOODS_ORDER_DETAIL add constraint FK_TSADV_GOODS_ORDER_DETAIL_GOODS_ORDER foreign key (GOODS_ORDER_ID) references TSADV_GOODS_ORDER(ID);
create index IDX_TSADV_GOODS_ORDER_DETAIL_GOODS on TSADV_GOODS_ORDER_DETAIL (GOODS_ID);
create index IDX_TSADV_GOODS_ORDER_DETAIL_GOODS_ORDER on TSADV_GOODS_ORDER_DETAIL (GOODS_ORDER_ID);
