alter table TSADV_BUDGET_HEADER add constraint FK_TSADV_BUDGET_HEADER_BUDGET foreign key (BUDGET_ID) references TSADV_BUDGET(ID);
alter table TSADV_BUDGET_HEADER add constraint FK_TSADV_BUDGET_HEADER_ORGANIZATION_GROUP foreign key (ORGANIZATION_GROUP_ID) references BASE_ORGANIZATION_GROUP(ID);
create index IDX_TSADV_BUDGET_HEADER_BUDGET on TSADV_BUDGET_HEADER (BUDGET_ID);
create index IDX_TSADV_BUDGET_HEADER_ORGANIZATION_GROUP on TSADV_BUDGET_HEADER (ORGANIZATION_GROUP_ID);
