alter table TSADV_BUDGET_REQUEST add constraint FK_TSADV_BUDGET_REQUEST_CITY foreign key (CITY_ID) references BASE_DIC_CITY(ID);
create index IDX_TSADV_BUDGET_REQUEST_CITY on TSADV_BUDGET_REQUEST (CITY_ID);
