alter table TSADV_INTERVIEW add constraint FK_TSADV_INTERVIEW_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
create index IDX_TSADV_INTERVIEW_ATTACHMENT on TSADV_INTERVIEW (ATTACHMENT_ID);
