alter table TSADV_ABSENCE_REQUEST add constraint FK_TSADV_ABSENCE_REQUEST_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
create index IDX_TSADV_ABSENCE_REQUEST_ATTACHMENT on TSADV_ABSENCE_REQUEST (ATTACHMENT_ID);
