alter table TSADV_AGREEMENT_DOCUMENT add constraint FK_TSADV_AGREEMENT_DOCUMENT_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table TSADV_AGREEMENT_DOCUMENT add constraint FK_TSADV_AGREEMENT_DOCUMENT_AGREEMENT foreign key (AGREEMENT_ID) references TSADV_AGREEMENT(ID);
create index IDX_TSADV_AGREEMENT_DOCUMENT_FILE on TSADV_AGREEMENT_DOCUMENT (FILE_ID);
create index IDX_TSADV_AGREEMENT_DOCUMENT_AGREEMENT on TSADV_AGREEMENT_DOCUMENT (AGREEMENT_ID);
