alter table TSADV_SALARY add constraint FK_TSADV_SALARY_SALARY_REQUEST foreign key (SALARY_REQUEST_ID) references TSADV_SALARY_REQUEST(ID);
create index IDX_TSADV_SALARY_SALARY_REQUEST on TSADV_SALARY (SALARY_REQUEST_ID);
