alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_ADDRESS_TYPE foreign key (ADDRESS_TYPE_ID) references TSADV_DIC_ADDRESS_TYPE(ID);
alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_COUNTRY foreign key (COUNTRY_ID) references BASE_DIC_COUNTRY(ID);
alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_STATUS foreign key (STATUS_ID) references TSADV_DIC_REQUEST_STATUS(ID);
alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_BASE_ADDRESS foreign key (BASE_ADDRESS_ID) references TSADV_ADDRESS(ID);
create index IDX_TSADV_ADDRESS_REQUEST_ADDRESS_TYPE on TSADV_ADDRESS_REQUEST (ADDRESS_TYPE_ID);
create index IDX_TSADV_ADDRESS_REQUEST_COUNTRY on TSADV_ADDRESS_REQUEST (COUNTRY_ID);
create index IDX_TSADV_ADDRESS_REQUEST_ATTACHMENT on TSADV_ADDRESS_REQUEST (ATTACHMENT_ID);
create index IDX_TSADV_ADDRESS_REQUEST_STATUS on TSADV_ADDRESS_REQUEST (STATUS_ID);
