alter table TSADV_BPM_ROLES_LINK add constraint FK_TSADV_BPM_ROLES_LINK_PROC_DEFINITON foreign key (PROC_DEFINITON_ID) references BPM_PROC_DEFINITION(ID);
alter table TSADV_BPM_ROLES_LINK add constraint FK_TSADV_BPM_ROLES_LINK_BPM_ROLE foreign key (BPM_ROLE_ID) references BPM_PROC_ROLE(ID);
alter table TSADV_BPM_ROLES_LINK add constraint FK_TSADV_BPM_ROLES_LINK_HR_ROLE foreign key (HR_ROLE_ID) references TSADV_DIC_HR_ROLE(ID);
create index IDX_TSADV_BPM_ROLES_LINK_UK_PROC_DEFINITON_ID on TSADV_BPM_ROLES_LINK (PROC_DEFINITON_ID) where DELETE_TS is null ;
create index IDX_TSADV_BPM_ROLES_LINK_PROC_DEFINITON on TSADV_BPM_ROLES_LINK (PROC_DEFINITON_ID);
create index IDX_TSADV_BPM_ROLES_LINK_BPM_ROLE on TSADV_BPM_ROLES_LINK (BPM_ROLE_ID);
create index IDX_TSADV_BPM_ROLES_LINK_HR_ROLE on TSADV_BPM_ROLES_LINK (HR_ROLE_ID);
