alter table TSADV_BPM_ROLES_DEFINER add constraint FK_TSADV_BPM_ROLES_DEFINER_PROC_MODEL foreign key (PROC_MODEL_ID) references BPM_PROC_MODEL(ID);
create unique index IDX_TSADV_BPM_ROLES_DEFINER_UK_PROC_MODEL_ID on TSADV_BPM_ROLES_DEFINER (PROC_MODEL_ID) where DELETE_TS is null ;
create index IDX_TSADV_BPM_ROLES_DEFINER_PROC_MODEL on TSADV_BPM_ROLES_DEFINER (PROC_MODEL_ID);
