alter table TSADV_LOOKUP_VALUE add constraint FK_TSADV_LOOKUP_VALUE_LOOKUP_TYPE foreign key (LOOKUP_TYPE_ID) references TSADV_LOOKUP_TYPE(ID);
create index IDX_TSADV_LOOKUP_VALUE_LOOKUP_TYPE on TSADV_LOOKUP_VALUE (LOOKUP_TYPE_ID);
