alter table TSADV_INSURANCE_CONTRACT add constraint FK_TSADV_INSURANCE_CONTRACT_COMPANY foreign key (COMPANY_ID) references TSADV_DIC_COMPANY(ID);
alter table TSADV_INSURANCE_CONTRACT add constraint FK_TSADV_INSURANCE_CONTRACT_RESPONSIBLE foreign key (RESPONSIBLE_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_INSURANCE_CONTRACT_COMPANY on TSADV_INSURANCE_CONTRACT (COMPANY_ID);
create index IDX_TSADV_INSURANCE_CONTRACT_RESPONSIBLE on TSADV_INSURANCE_CONTRACT (RESPONSIBLE_ID);
