alter table TSADV_ATTACHMENT_TYPE add constraint FK_TSADV_ATTACHMENT_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_ATTACHMENT_TYPE_COMPANY on TSADV_ATTACHMENT_TYPE (COMPANY_ID);
