alter table TSADV_DIC_DURATION add constraint FK_TSADV_DIC_DURATION_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_DURATION_COMPANY on TSADV_DIC_DURATION (COMPANY_ID);
