alter table TSADV_DIC_COURSE_CYCLE add constraint FK_TSADV_DIC_COURSE_CYCLE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_COURSE_CYCLE_COMPANY on TSADV_DIC_COURSE_CYCLE (COMPANY_ID);
