alter table TSADV_CONTROL_STAGE add constraint FK_TSADV_CONTROL_STAGE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_CONTROL_STAGE_COMPANY on TSADV_CONTROL_STAGE (COMPANY_ID);
