alter table TSADV_INSURED_PERSON add constraint FK_TSADV_INSURED_PERSON_ADDRESS foreign key (ADDRESS_ID) references BASE_ADDRESS(ID);
create index IDX_TSADV_INSURED_PERSON_ADDRESS on TSADV_INSURED_PERSON (ADDRESS_ID);
