alter table TSADV_DIC_FORM_STUDY add constraint FK_TSADV_DIC_FORM_STUDY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_FORM_STUDY_COMPANY on TSADV_DIC_FORM_STUDY (COMPANY_ID);
