alter table TSADV_CERTIFICATE_TEMPLATE drop constraint if exists FK_TSADV_CERTIFICATE_TEMPLATE_ORGANIZATION;
alter table TSADV_CERTIFICATE_TEMPLATE add constraint FK_TSADV_CERTIFICATE_TEMPLATE_ORGANIZATION foreign key (ORGANIZATION_ID) references BASE_ORGANIZATION_GROUP(ID);
create index if not exists IDX_TSADV_CERTIFICATE_TEMPLATE_ORGANIZATION on TSADV_CERTIFICATE_TEMPLATE (ORGANIZATION_ID);
create unique index  if not exists  IDX_TSADV_CERTIFICATE_TEMPLATE_UK_IDENTITY on TSADV_CERTIFICATE_TEMPLATE (receiving_type_id, language_id, show_salary, ORGANIZATION_ID) where DELETE_TS is null;