alter table TSADV_DIC_GOODS_CATEGORY add constraint FK_TSADV_DIC_GOODS_CATEGORY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_GOODS_CATEGORY_COMPANY on TSADV_DIC_GOODS_CATEGORY (COMPANY_ID);
