alter table TSADV_GRADE_GROUP add constraint FK_TSADV_GRADE_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_GRADE_GROUP_COMPANY on TSADV_GRADE_GROUP (COMPANY_ID);
