alter table TSADV_DIC_REASON_BENIFIT add constraint FK_TSADV_DIC_REASON_BENIFIT_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_REASON_BENIFIT_COMPANY on TSADV_DIC_REASON_BENIFIT (COMPANY_ID);
