alter table TSADV_DIC_PRIORITY add constraint FK_TSADV_DIC_PRIORITY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_PRIORITY_COMPANY on TSADV_DIC_PRIORITY (COMPANY_ID);
