alter table TSADV_DIC_INDUSTRY add constraint FK_TSADV_DIC_INDUSTRY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_INDUSTRY_COMPANY on TSADV_DIC_INDUSTRY (COMPANY_ID);
