alter table TSADV_INCIDENT_TYPE add constraint FK_TSADV_INCIDENT_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_INCIDENT_TYPE_COMPANY on TSADV_INCIDENT_TYPE (COMPANY_ID);
