alter table TSADV_DIC_NATIONALITY add constraint FK_TSADV_DIC_NATIONALITY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_NATIONALITY_COMPANY on TSADV_DIC_NATIONALITY (COMPANY_ID);
