alter table TSADV_DIC_CITIZENSHIP add constraint FK_TSADV_DIC_CITIZENSHIP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_CITIZENSHIP_COMPANY on TSADV_DIC_CITIZENSHIP (COMPANY_ID);
