alter table TSADV_DIC_COMPANY add constraint FK_TSADV_DIC_COMPANY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_COMPANY_COMPANY on TSADV_DIC_COMPANY (COMPANY_ID);
