alter table TSADV_RISKS_VIOLATIONS add constraint FK_TSADV_RISKS_VIOLATIONS_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_RISKS_VIOLATIONS_COMPANY on TSADV_RISKS_VIOLATIONS (COMPANY_ID);
