alter table TSADV_INSPECTION_TYPE add constraint FK_TSADV_INSPECTION_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_INSPECTION_TYPE_COMPANY on TSADV_INSPECTION_TYPE (COMPANY_ID);
