
alter table TSADV_CERTIFICATE_REQUEST add constraint FK_TSADV_CERTIFICATE_REQUEST_LANGUAGE foreign key (LANGUAGE_ID) references TSADV_DIC_LANGUAGE(ID);
create index IDX_TSADV_CERTIFICATE_REQUEST_LANGUAGE on TSADV_CERTIFICATE_REQUEST (LANGUAGE_ID);
