alter table TSADV_DIC_OPERATOR_CODE add constraint FK_TSADV_DIC_OPERATOR_CODE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_OPERATOR_CODE_COMPANY on TSADV_DIC_OPERATOR_CODE (COMPANY_ID);
