alter table TSADV_HARMFUL_FACTOR_TYPE add constraint FK_TSADV_HARMFUL_FACTOR_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_HARMFUL_FACTOR_TYPE_COMPANY on TSADV_HARMFUL_FACTOR_TYPE (COMPANY_ID);
