alter table TSADV_DIC_REGISTER_GROUP add constraint FK_TSADV_DIC_REGISTER_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_REGISTER_GROUP_COMPANY on TSADV_DIC_REGISTER_GROUP (COMPANY_ID);
