alter table TSADV_DIC_DISMISSAL_REASON add constraint FK_TSADV_DIC_DISMISSAL_REASON_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_DISMISSAL_REASON_COMPANY on TSADV_DIC_DISMISSAL_REASON (COMPANY_ID);
