alter table TSADV_COURSE_SCHEDULE add constraint FK_TSADV_COURSE_SCHEDULE_COURSE foreign key (COURSE_ID) references TSADV_COURSE(ID);
alter table TSADV_COURSE_SCHEDULE add constraint FK_TSADV_COURSE_SCHEDULE_LEARNING_CENTER foreign key (LEARNING_CENTER_ID) references TSADV_DIC_LEARNING_CENTER(ID);
create index IDX_TSADV_COURSE_SCHEDULE_COURSE on TSADV_COURSE_SCHEDULE (COURSE_ID);
create index IDX_TSADV_COURSE_SCHEDULE_LEARNING_CENTER on TSADV_COURSE_SCHEDULE (LEARNING_CENTER_ID);
