alter table TSADV_DICDELIVERY_ADDRESS add constraint FK_TSADV_DICDELIVERY_ADDRESS_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DICDELIVERY_ADDRESS_COMPANY on TSADV_DICDELIVERY_ADDRESS (COMPANY_ID);
