alter table TSADV_DIC_MILITARY_RANK add constraint FK_TSADV_DIC_MILITARY_RANK_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_MILITARY_RANK_COMPANY on TSADV_DIC_MILITARY_RANK (COMPANY_ID);
