create table TSADV_IMPROVING_PROFESSIONAL_SKILLS_FILE_DESCRIPTOR_LINK (
    IMPROVING_PROFESSIONAL_SKILLS_ID uuid,
    FILE_DESCRIPTOR_ID uuid,
    primary key (IMPROVING_PROFESSIONAL_SKILLS_ID, FILE_DESCRIPTOR_ID)
);
