alter table TSADV_INSURANCE_CONTRACT drop constraint if exists FK_TSADV_INSURANCE_CONTRACT_COMPANY;
alter table TSADV_INSURANCE_CONTRACT add constraint FK_TSADV_INSURANCE_CONTRACT_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index if not exists IDX_TSADV_INSURANCE_CONTRACT_COMPANY on TSADV_INSURANCE_CONTRACT (COMPANY_ID);
