alter table TSADV_ABSENCE_REQUEST add constraint FK_TSADV_ABSENCE_REQUEST_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_ABSENCE_REQUEST_PERSON_GROUP on TSADV_ABSENCE_REQUEST (PERSON_GROUP_ID);
