create table TSADV_IMPROVING_PROFESSIONAL_SKILLS_REQ_FILE_DESCRIPTOR_LINK (
    IMPROVING_PROFESSIONAL_SKILLS_REQUEST_ID uuid,
    FILE_DESCRIPTOR_ID uuid,
    primary key (IMPROVING_PROFESSIONAL_SKILLS_REQUEST_ID, FILE_DESCRIPTOR_ID)
);
