alter table TSADV_CONTROL_TYPE add constraint FK_TSADV_CONTROL_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_CONTROL_TYPE_COMPANY on TSADV_CONTROL_TYPE (COMPANY_ID);
