alter table TSADV_INSURED_PERSON drop constraint if exists FK_TSADV_INSURED_PERSON_COMPANY;
alter table TSADV_INSURED_PERSON add constraint FK_TSADV_INSURED_PERSON_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index if not exists IDX_TSADV_INSURED_PERSON_INSURANCE_CONTRACT on TSADV_INSURED_PERSON (INSURANCE_CONTRACT_ID);