alter table TSADV_DIC_MONTH add constraint FK_TSADV_DIC_MONTH_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_MONTH_COMPANY on TSADV_DIC_MONTH (COMPANY_ID);
