alter table TSADV_DIC_POSTING_CHANNEL add constraint FK_TSADV_DIC_POSTING_CHANNEL_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_POSTING_CHANNEL_COMPANY on TSADV_DIC_POSTING_CHANNEL (COMPANY_ID);
