alter table TSADV_INTOXICATION_TYPE add constraint FK_TSADV_INTOXICATION_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_INTOXICATION_TYPE_COMPANY on TSADV_INTOXICATION_TYPE (COMPANY_ID);
