alter table TSADV_EXCAVATION add constraint FK_TSADV_EXCAVATION_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_EXCAVATION_COMPANY on TSADV_EXCAVATION (COMPANY_ID);
