alter table TSADV_BPROC_ACTORS add constraint FK_TSADV_BPROC_ACTORS_HR_ROLE foreign key (HR_ROLE_ID) references TSADV_DIC_HR_ROLE(ID);
alter table TSADV_BPROC_ACTORS add constraint FK_TSADV_BPROC_ACTORS_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_TSADV_BPROC_ACTORS_HR_ROLE on TSADV_BPROC_ACTORS (HR_ROLE_ID);
create index IDX_TSADV_BPROC_ACTORS_USER on TSADV_BPROC_ACTORS (USER_ID);
