alter table TSADV_ABSENCE add constraint FK_TSADV_ABSENCE_PURPOSE foreign key (PURPOSE_ID) references TSADV_DIC_ABSENCE_PURPOSE(ID);
create index IDX_TSADV_ABSENCE_PURPOSE on TSADV_ABSENCE (PURPOSE_ID);
