alter table TSADV_INVESTIGATION_TYPE add constraint FK_TSADV_INVESTIGATION_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_INVESTIGATION_TYPE_COMPANY on TSADV_INVESTIGATION_TYPE (COMPANY_ID);
