alter table TSADV_ABSENCE_REQUEST add constraint FK_TSADV_ABSENCE_REQUEST_PURPOSE foreign key (PURPOSE_ID) references TSADV_DIC_ABSENCE_PURPOSE(ID);
create index IDX_TSADV_ABSENCE_REQUEST_PURPOSE on TSADV_ABSENCE_REQUEST (PURPOSE_ID);
