alter table TSADV_EVENT_TYPE add constraint FK_TSADV_EVENT_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_EVENT_TYPE_COMPANY on TSADV_EVENT_TYPE (COMPANY_ID);
