alter table TSADV_SUR_CHARGE_NAME add constraint FK_TSADV_SUR_CHARGE_NAME_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_SUR_CHARGE_NAME_COMPANY on TSADV_SUR_CHARGE_NAME (COMPANY_ID);
