alter table TSADV_DIC_LANGUAGE add constraint FK_TSADV_DIC_LANGUAGE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_LANGUAGE_COMPANY on TSADV_DIC_LANGUAGE (COMPANY_ID);
