alter table TSADV_PUNISHMENT_TYPE add constraint FK_TSADV_PUNISHMENT_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_PUNISHMENT_TYPE_COMPANY on TSADV_PUNISHMENT_TYPE (COMPANY_ID);
