alter table TSADV_INSURED_PERSON add constraint FK_TSADV_INSURED_PERSON_ADDRESS foreign key (ADDRESS_ID) references TSADV_DIC_ADDRESS_TYPE(ID);
create index IDX_TSADV_INSURED_PERSON_ADDRESS on TSADV_INSURED_PERSON (ADDRESS_ID);
