alter table TSADV_REABILITATION_TYPE add constraint FK_TSADV_REABILITATION_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_REABILITATION_TYPE_COMPANY on TSADV_REABILITATION_TYPE (COMPANY_ID);
