alter table TSADV_TRAUMA_LEVEL add constraint FK_TSADV_TRAUMA_LEVEL_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_TRAUMA_LEVEL_COMPANY on TSADV_TRAUMA_LEVEL (COMPANY_ID);
