alter table TSADV_OBJECT_TYPE add constraint FK_TSADV_OBJECT_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_OBJECT_TYPE_COMPANY on TSADV_OBJECT_TYPE (COMPANY_ID);
