alter table TSADV_DIC_TRADE_UNION add constraint FK_TSADV_DIC_TRADE_UNION_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_TRADE_UNION_COMPANY on TSADV_DIC_TRADE_UNION (COMPANY_ID);
