alter table TSADV_DIC_TRANSPORT_CLASS add constraint FK_TSADV_DIC_TRANSPORT_CLASS_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_TRANSPORT_CLASS_COMPANY on TSADV_DIC_TRANSPORT_CLASS (COMPANY_ID);
