alter table TSADV_INSPECTION_CATEGORY add constraint FK_TSADV_INSPECTION_CATEGORY_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_INSPECTION_CATEGORY_COMPANY on TSADV_INSPECTION_CATEGORY (COMPANY_ID);
