alter table TSADV_DIC_TROOPS_STRUCTURE add constraint FK_TSADV_DIC_TROOPS_STRUCTURE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_TROOPS_STRUCTURE_COMPANY on TSADV_DIC_TROOPS_STRUCTURE (COMPANY_ID);
