alter table TSADV_DIC_FIRE_RESISTANCE add constraint FK_TSADV_DIC_FIRE_RESISTANCE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_FIRE_RESISTANCE_COMPANY on TSADV_DIC_FIRE_RESISTANCE (COMPANY_ID);
