alter table TSADV_STATUS_MSDS add constraint FK_TSADV_STATUS_MSDS_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_STATUS_MSDS_COMPANY on TSADV_STATUS_MSDS (COMPANY_ID);
