alter table TSADV_DISABILITY_GROUP add constraint FK_TSADV_DISABILITY_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DISABILITY_GROUP_COMPANY on TSADV_DISABILITY_GROUP (COMPANY_ID);
