alter table BASE_ORGANIZATION_GROUP add constraint FK_BASE_ORGANIZATION_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_BASE_ORGANIZATION_GROUP_COMPANY on BASE_ORGANIZATION_GROUP (COMPANY_ID);
