alter table TSADV_DISCONFORMITY_TYPE add constraint FK_TSADV_DISCONFORMITY_TYPE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DISCONFORMITY_TYPE_COMPANY on TSADV_DISCONFORMITY_TYPE (COMPANY_ID);
