alter table TSADV_CERTIFICATE_TEMPLATE rename column order_ to order___u55392 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column is_default to is_default__u92714 ;
alter table TSADV_CERTIFICATE_TEMPLATE alter column is_default__u92714 drop not null ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column active to active__u11904 ;
alter table TSADV_CERTIFICATE_TEMPLATE alter column active__u11904 drop not null ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column is_system_record to is_system_record__u18816 ;
alter table TSADV_CERTIFICATE_TEMPLATE alter column is_system_record__u18816 drop not null ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column code to code__u83106 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column end_date to end_date__u06800 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column start_date to start_date__u60772 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column description5 to description5__u74917 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column lang_value5 to lang_value5__u71335 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column description4 to description4__u29312 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column lang_value4 to lang_value4__u14958 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column description3 to description3__u72636 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column lang_value3 to lang_value3__u80031 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column description2 to description2__u55555 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column lang_value2 to lang_value2__u17519 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column description1 to description1__u41253 ;
alter table TSADV_CERTIFICATE_TEMPLATE rename column lang_value1 to lang_value1__u62731 ;
alter table TSADV_CERTIFICATE_TEMPLATE alter column lang_value1__u62731 drop not null ;
