alter table TSADV_DIC_EXAM_RESULTS add constraint FK_TSADV_DIC_EXAM_RESULTS_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_EXAM_RESULTS_COMPANY on TSADV_DIC_EXAM_RESULTS (COMPANY_ID);
