alter table TSADV_DIC_COURSE_FORMAT add constraint FK_TSADV_DIC_COURSE_FORMAT_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_DIC_COURSE_FORMAT_COMPANY on TSADV_DIC_COURSE_FORMAT (COMPANY_ID);
