alter table TSADV_ENROLLMENT add constraint FK_TSADV_ENROLLMENT_COURSE_SCHEDULE foreign key (COURSE_SCHEDULE_ID) references TSADV_COURSE_SCHEDULE(ID);
create index IDX_TSADV_ENROLLMENT_COURSE_SCHEDULE on TSADV_ENROLLMENT (COURSE_SCHEDULE_ID);
