create table TSADV_ABSENCE_RVD_REQUEST (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    LEGACY_ID varchar(255),
    ORGANIZATION_BIN varchar(255),
    INTEGRATION_USER_LOGIN varchar(255),
    REQUEST_NUMBER bigint not null,
    STATUS_ID uuid not null,
    REQUEST_DATE date not null,
    COMMENT_ varchar(3000),
    --
    PERSON_GROUP_ID uuid,
    TYPE_ID uuid,
    PURPOSE_ID uuid,
    PURPOSE_TEXT varchar(2000),
    TIME_OF_STARTING timestamp,
    TIME_OF_FINISHING timestamp,
    TOTAL_HOURS integer,
    COMPENCATION boolean,
    VACATION_DAY boolean,
    ACQUAINTED boolean,
    AGREE boolean,
    --
    primary key (ID)
);