alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS REQUEST_NUMBER bigint ^
update TSADV_ASSIGNED_PERFORMANCE_PLAN set REQUEST_NUMBER = 0 where REQUEST_NUMBER is null ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN alter column REQUEST_NUMBER set not null ;
-- alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column STATUS_ID uuid ^
-- update TSADV_ASSIGNED_PERFORMANCE_PLAN set STATUS_ID = <default_value> ;
-- alter table TSADV_ASSIGNED_PERFORMANCE_PLAN alter column STATUS_ID set not null ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS STATUS_ID uuid;
update TSADV_ASSIGNED_PERFORMANCE_PLAN set STATUS_ID = drs.id FROM (SELECT id FROM tsadv_dic_request_status rs WHERE rs.code = 'DRAFT' LIMIT 1) drs where STATUS_ID is null;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN alter column STATUS_ID set not null;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS LEGACY_ID varchar(255) ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS INTEGRATION_USER_LOGIN varchar(255) ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS REQUEST_DATE date ^
update TSADV_ASSIGNED_PERFORMANCE_PLAN set REQUEST_DATE = current_date where REQUEST_DATE is null ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN alter column REQUEST_DATE set not null ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS COMMENT_ varchar(3000) ;
alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add column IF NOT EXISTS ORGANIZATION_BIN varchar(255) ;
