create table TSADV_CHANGE_ABSENCE_DAYS_REQUEST_FILE_DESCRIPTOR_LINK (
    CHANGE_ABSENCE_DAYS_REQUEST_ID uuid,
    FILE_DESCRIPTOR_ID uuid,
    primary key (CHANGE_ABSENCE_DAYS_REQUEST_ID, FILE_DESCRIPTOR_ID)
);
