alter table TSADV_INSURED_PERSON add constraint FK_TSADV_INSURED_PERSON_STATEMENT_FILE foreign key (STATEMENT_FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_INSURED_PERSON_STATEMENT_FILE on TSADV_INSURED_PERSON (STATEMENT_FILE_ID);
