create table TSADV_CHANGE_ABSENCE_DAYS_REQUEST (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    LEGACY_ID varchar(255),
    ORGANIZATION_BIN varchar(255),
    INTEGRATION_USER_LOGIN varchar(255),
    REQUEST_NUMBER bigint not null,
    STATUS_ID uuid not null,
    REQUEST_DATE date not null,
    COMMENT_ varchar(3000),
    --
    REQUEST_TYPE_ID uuid,
    EMPLOYEE_ID uuid,
    VACATION_ID uuid,
    SCHEDULE_START_DATE date,
    SCHEDULE_END_DATE date,
    NEW_START_DATE date,
    NEW_END_DATE date,
    PERIOD_START_DATE date,
    PERIOD_END_DATE date,
    AGREE boolean not null,
    FAMILIARIZATION boolean not null,
    PURPOSE_TEXT text,
    PURPOSE_ID uuid,
    --
    primary key (ID)
);