alter table BASE_PERSON_GROUP add constraint FK_BASE_PERSON_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_BASE_PERSON_GROUP_COMPANY on BASE_PERSON_GROUP (COMPANY_ID);
