alter table TSADV_COURSE_CERTIFICATE add constraint FK_TSADV_COURSE_CERTIFICATE_CERTIFICATE foreign key (CERTIFICATE_ID) references REPORT_REPORT(ID);
alter table TSADV_COURSE_CERTIFICATE add constraint FK_TSADV_COURSE_CERTIFICATE_COURSE foreign key (COURSE_ID) references TSADV_COURSE(ID);
create index IDX_TSADV_COURSE_CERTIFICATE_CERTIFICATE on TSADV_COURSE_CERTIFICATE (CERTIFICATE_ID);
create index IDX_TSADV_COURSE_CERTIFICATE_COURSE on TSADV_COURSE_CERTIFICATE (COURSE_ID);
