alter table BASE_ASSIGNMENT_GROUP add constraint FK_BASE_ASSIGNMENT_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_BASE_ASSIGNMENT_GROUP_COMPANY on BASE_ASSIGNMENT_GROUP (COMPANY_ID);
