alter table TSADV_ASSIGNED_PERFORMANCE_PLAN add constraint FK_TSADV_ASSIGNED_PERFORMANCE_PLAN_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_ASSIGNED_PERFORMANCE_PLAN_FILE on TSADV_ASSIGNED_PERFORMANCE_PLAN (FILE_ID);
