alter table BASE_ASSIGNMENT_GROUP add constraint FK_BASE_ASSIGNMENT_GROUP_JOB_GROUP foreign key (JOB_GROUP_ID) references TSADV_JOB_GROUP(ID);
create index IDX_BASE_ASSIGNMENT_GROUP_JOB_GROUP on BASE_ASSIGNMENT_GROUP (JOB_GROUP_ID);
