alter table TSADV_PORTAL_FEEDBACK add constraint FK_TSADV_PORTAL_FEEDBACK_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
alter table TSADV_PORTAL_FEEDBACK add constraint FK_TSADV_PORTAL_FEEDBACK_CATEGORY foreign key (CATEGORY_ID) references TSADV_DIC_PORTAL_FEEDBACK_QUESTION(ID);
create index IDX_TSADV_PORTAL_FEEDBACK_COMPANY on TSADV_PORTAL_FEEDBACK (COMPANY_ID);
create index IDX_TSADV_PORTAL_FEEDBACK_CATEGORY on TSADV_PORTAL_FEEDBACK (CATEGORY_ID);
