alter table BASE_ASSIGNMENT_GROUP add constraint FK_BASE_ASSIGNMENT_GROUP_GRADE_GROUP foreign key (GRADE_GROUP_ID) references TSADV_GRADE_GROUP(ID);
create index IDX_BASE_ASSIGNMENT_GROUP_GRADE_GROUP on BASE_ASSIGNMENT_GROUP (GRADE_GROUP_ID);
