-- update TSADV_ORG_STRUCTURE_REQUEST_DETAIL set ORG_STRUCTURE_REQUEST_ID = <default_value> where ORG_STRUCTURE_REQUEST_ID is null ;
alter table TSADV_ORG_STRUCTURE_REQUEST_DETAIL alter column ORG_STRUCTURE_REQUEST_ID set not null ;
