alter table BASE_POSITION_GROUP add constraint FK_BASE_POSITION_GROUP_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_BASE_POSITION_GROUP_COMPANY on BASE_POSITION_GROUP (COMPANY_ID);
