alter table BASE_ASSIGNMENT_GROUP add constraint FK_BASE_ASSIGNMENT_GROUP_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_BASE_ASSIGNMENT_GROUP_PERSON_GROUP on BASE_ASSIGNMENT_GROUP (PERSON_GROUP_ID);
