alter table TSADV_INSURED_PERSON add constraint FK_TSADV_INSURED_PERSON_ADDRESS_TYPE foreign key (ADDRESS_TYPE_ID) references TSADV_DIC_ADDRESS_TYPE(ID);
create index IDX_TSADV_INSURED_PERSON_ADDRESS_TYPE on TSADV_INSURED_PERSON (ADDRESS_TYPE_ID);
