alter table TSADV_BOOK_VIEW add constraint FK_TSADV_BOOK_VIEW_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_BOOK_VIEW add constraint FK_TSADV_BOOK_VIEW_BOOK foreign key (BOOK_ID) references TSADV_BOOK(ID);
create index IDX_TSADV_BOOK_VIEW_PERSON_GROUP on TSADV_BOOK_VIEW (PERSON_GROUP_ID);
create index IDX_TSADV_BOOK_VIEW_BOOK on TSADV_BOOK_VIEW (BOOK_ID);
