alter table TSADV_STANDARD_SCHEDULE add constraint FK_TSADV_STANDARD_SCHEDULE_COMPANY foreign key (COMPANY_ID) references BASE_DIC_COMPANY(ID);
create index IDX_TSADV_STANDARD_SCHEDULE_COMPANY on TSADV_STANDARD_SCHEDULE (COMPANY_ID);
