alter table TSADV_BPM_ROLES_DEFINER add column MANAGER_LAUNCHES boolean ^
update TSADV_BPM_ROLES_DEFINER set MANAGER_LAUNCHES = false where MANAGER_LAUNCHES is null ;
alter table TSADV_BPM_ROLES_DEFINER alter column MANAGER_LAUNCHES set not null ;
alter table TSADV_BPM_ROLES_DEFINER add column ACTIVE_SUP_MANAGER_EXCLUSION boolean ^
update TSADV_BPM_ROLES_DEFINER set ACTIVE_SUP_MANAGER_EXCLUSION = false where ACTIVE_SUP_MANAGER_EXCLUSION is null ;
alter table TSADV_BPM_ROLES_DEFINER alter column ACTIVE_SUP_MANAGER_EXCLUSION set not null ;
