alter table TSADV_ADDRESS_REQUEST add constraint FK_TSADV_ADDRESS_REQUEST_KATO foreign key (KATO_ID) references TSADV_DIC_KATO(ID);
create index IDX_TSADV_ADDRESS_REQUEST_KATO on TSADV_ADDRESS_REQUEST (KATO_ID);
