alter table TSADV_DIC_ABSENCE_TYPE add column IS_SCHEDULE_OFFSETS_REQUEST boolean ^
update TSADV_DIC_ABSENCE_TYPE set IS_SCHEDULE_OFFSETS_REQUEST = false where IS_SCHEDULE_OFFSETS_REQUEST is null ;
alter table TSADV_DIC_ABSENCE_TYPE alter column IS_SCHEDULE_OFFSETS_REQUEST set not null ;
