alter table TSADV_ABSENCE_BALANCE drop column OVERALL_BALANCE_DAYS__U41787 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column BALANCE_DAYS__U71219 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column ADDITIONAL_BALANCE_DAYS__U50712 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column DAYS_SPENT__U77612 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column EXTRA_DAYS_SPENT__U70125 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column LONG_ABSENCE_DAYS__U32493 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column ADD_BALANCE_DAYS_AIMS__U17592 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column ECOLOGICAL_DUE_DAYS__U73127 cascade ;
alter table TSADV_ABSENCE_BALANCE drop column DISABILITY_DUE_DAYS__U59269 cascade ;
