alter table TSADV_POSITION_COURSE add constraint FK_TSADV_POSITION_COURSE_POSITION_GROUP foreign key (POSITION_GROUP_ID) references BASE_POSITION_GROUP(ID);
alter table TSADV_POSITION_COURSE add constraint FK_TSADV_POSITION_COURSE_COURSE foreign key (COURSE_ID) references TSADV_COURSE(ID);
create index IDX_TSADV_POSITION_COURSE_POSITION_GROUP on TSADV_POSITION_COURSE (POSITION_GROUP_ID);
create index IDX_TSADV_POSITION_COURSE_COURSE on TSADV_POSITION_COURSE (COURSE_ID);
