alter table TSADV_COURSE add constraint FK_TSADV_COURSE_PROGRAMM_CODE foreign key (PROGRAMM_CODE_ID) references TSADV_DIC_PROGRAMM_CODE(ID);
create index IDX_TSADV_COURSE_PROGRAMM_CODE on TSADV_COURSE (PROGRAMM_CODE_ID);
