alter table TSADV_PERSON_PAYSLIP add constraint FK_TSADV_PERSON_PAYSLIP_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_PAYSLIP_PERSON_GROUP on TSADV_PERSON_PAYSLIP (PERSON_GROUP_ID);
