alter table TSADV_COURSE add constraint FK_TSADV_COURSE_ASSESSMENT_METHOD foreign key (ASSESSMENT_METHOD_ID) references TSADV_DIC_ASSESSMENT_METHOD(ID);
create index IDX_TSADV_COURSE_ASSESSMENT_METHOD on TSADV_COURSE (ASSESSMENT_METHOD_ID);
