create table TSADV_SCHEDULE_OFFSETS_REQUEST_FILE_DESCRIPTOR_LINK (
    SCHEDULE_OFFSETS_REQUEST_ID uuid,
    FILE_DESCRIPTOR_ID uuid,
    primary key (SCHEDULE_OFFSETS_REQUEST_ID, FILE_DESCRIPTOR_ID)
);
