alter table TSADV_LIST_OF_DOCUMENT add constraint FK_TSADV_LIST_OF_DOCUMENT_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_LIST_OF_DOCUMENT add constraint FK_TSADV_LIST_OF_DOCUMENT_TYPE foreign key (TYPE_ID) references TSADV_DIC_DOCUMENT_TYPE(ID);
alter table TSADV_LIST_OF_DOCUMENT add constraint FK_TSADV_LIST_OF_DOCUMENT_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_LIST_OF_DOCUMENT_PERSON_GROUP on TSADV_LIST_OF_DOCUMENT (PERSON_GROUP_ID);
create index IDX_TSADV_LIST_OF_DOCUMENT_TYPE on TSADV_LIST_OF_DOCUMENT (TYPE_ID);
create index IDX_TSADV_LIST_OF_DOCUMENT_FILE on TSADV_LIST_OF_DOCUMENT (FILE_ID);
