alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS rename column responsible_person_id to responsible_person_id__u36554 ;
alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS alter column responsible_person_id__u36554 drop not null ;
alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS drop constraint FK_TSADV_ORGANIZATION_INCENTIVE_INDICATORS_RESPONSIBLE_PERSON ;
drop index IDX_TSADV_ORGANIZATION_INCENTIVE_INDICATORS_RESPONSIBLE_PERSON ;
-- alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS add column RESPONSIBLE_POSITION_ID uuid ^
-- update TSADV_ORGANIZATION_INCENTIVE_INDICATORS set RESPONSIBLE_POSITION_ID = <default_value> ;
-- alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS alter column RESPONSIBLE_POSITION_ID set not null ;
alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS add column RESPONSIBLE_POSITION_ID uuid not null ;
