alter table TSADV_BENEFICIARY add constraint FK_TSADV_BENEFICIARY_SOC_STATUS foreign key (SOC_STATUS_ID) references TSADV_DIC_SOC_STATUS(ID);
create index IDX_TSADV_BENEFICIARY_SOC_STATUS on TSADV_BENEFICIARY (SOC_STATUS_ID);
