alter table TSADV_PAYMENTS add constraint FK_TSADV_PAYMENTS_GRANTEES_AGREEMENT foreign key (GRANTEES_AGREEMENT_ID) references TSADV_GRANTEES_AGREEMENT(ID);
alter table TSADV_PAYMENTS add constraint FK_TSADV_PAYMENTS_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PAYMENTS_GRANTEES_AGREEMENT on TSADV_PAYMENTS (GRANTEES_AGREEMENT_ID);
create index IDX_TSADV_PAYMENTS_PERSON_GROUP on TSADV_PAYMENTS (PERSON_GROUP_ID);
