alter table TSADV_BPROC_REASSIGNMENT add constraint FK_TSADV_BPROC_REASSIGNMENT_ASSIGNEE foreign key (ASSIGNEE_ID) references SEC_USER(ID);
create index IDX_TSADV_BPROC_REASSIGNMENT_ASSIGNEE on TSADV_BPROC_REASSIGNMENT (ASSIGNEE_ID);
