alter table TSADV_LIST_OF_DOCUMENTS add constraint FK_TSADV_LIST_OF_DOCUMENTS_TYPE foreign key (TYPE_ID) references TSADV_DIC_DOCUMENT_TYPE(ID);
alter table TSADV_LIST_OF_DOCUMENTS add constraint FK_TSADV_LIST_OF_DOCUMENTS_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table TSADV_LIST_OF_DOCUMENTS add constraint FK_TSADV_LIST_OF_DOCUMENTS_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_LIST_OF_DOCUMENTS_TYPE on TSADV_LIST_OF_DOCUMENTS (TYPE_ID);
create index IDX_TSADV_LIST_OF_DOCUMENTS_FILE on TSADV_LIST_OF_DOCUMENTS (FILE_ID);
create index IDX_TSADV_LIST_OF_DOCUMENTS_PERSON_GROUP on TSADV_LIST_OF_DOCUMENTS (PERSON_GROUP_ID);