alter table TSADV_GUARDIAN add constraint FK_TSADV_GUARDIAN_GUARDIAN_TYPE foreign key (GUARDIAN_TYPE_ID) references TSADV_DIC_GUARDIAN_TYPE(ID);
alter table TSADV_GUARDIAN add constraint FK_TSADV_GUARDIAN_FIELD_OF_ACTIVITY foreign key (FIELD_OF_ACTIVITY_ID) references TSADV_DIC_FIELD_OF_ACTIVITY(ID);
alter table TSADV_GUARDIAN add constraint FK_TSADV_GUARDIAN_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_GUARDIAN_GUARDIAN_TYPE on TSADV_GUARDIAN (GUARDIAN_TYPE_ID);
create index IDX_TSADV_GUARDIAN_FIELD_OF_ACTIVITY on TSADV_GUARDIAN (FIELD_OF_ACTIVITY_ID);
create index IDX_TSADV_GUARDIAN_PERSON_GROUP on TSADV_GUARDIAN (PERSON_GROUP_ID);
