alter table TSADV_JOB_DESCRIPTION add constraint FK_TSADV_JOB_DESCRIPTION_POSITION_GROUP foreign key (POSITION_GROUP_ID) references BASE_POSITION_GROUP(ID);
alter table TSADV_JOB_DESCRIPTION add constraint FK_TSADV_JOB_DESCRIPTION_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table TSADV_JOB_DESCRIPTION add constraint FK_TSADV_JOB_DESCRIPTION_REQUEST foreign key (REQUEST_ID) references TSADV_JOB_DESCRIPTION_REQUEST(ID);
create index IDX_TSADV_JOB_DESCRIPTION_FILE on TSADV_JOB_DESCRIPTION (FILE_ID);
create index IDX_TSADV_JOB_DESCRIPTION_REQUEST on TSADV_JOB_DESCRIPTION (REQUEST_ID);
