alter table BASE_PERSON_GROUP add constraint FK_BASE_PERSON_GROUP_SOC_STATUS foreign key (SOC_STATUS_ID) references TSADV_DIC_SOC_STATUS(ID);
create index IDX_BASE_PERSON_GROUP_SOC_STATUS on BASE_PERSON_GROUP (SOC_STATUS_ID);
