alter table TSADV_BENEFICIARY add constraint FK_TSADV_BENEFICIARY_STREET_TYPE foreign key (STREET_TYPE_ID) references TSADV_DIC_STREET_TYPE(ID);
create index IDX_TSADV_BENEFICIARY_STREET_TYPE on TSADV_BENEFICIARY (STREET_TYPE_ID);
