alter table TSADV_BENEFICIARY add constraint FK_TSADV_BENEFICIARY_COUNTRY foreign key (COUNTRY_ID) references BASE_DIC_COUNTRY(ID);
create index IDX_TSADV_BENEFICIARY_COUNTRY on TSADV_BENEFICIARY (COUNTRY_ID);
