 alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS add column APPROVING_POSITION_ID uuid ^
 update TSADV_ORGANIZATION_INCENTIVE_INDICATORS set APPROVING_POSITION_ID = (select id from BASE_POSITION_GROUP limit 1) where APPROVING_POSITION_ID is null;
 alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS alter column APPROVING_POSITION_ID set not null ;
--alter table TSADV_ORGANIZATION_INCENTIVE_INDICATORS add column APPROVING_POSITION_ID uuid not null ;
