CREATE OR REPLACE VIEW public.tsadv_organization_incentive_month_result_short_view
AS SELECT a.id,
    a.month_result_id AS incentive_month_result_id,
    a.version,
    a.create_ts,
    a.created_by,
    a.update_ts,
    a.updated_by,
    a.delete_ts,
    a.deleted_by,
    a.company_id,
    a.period_,
    a.department_id,
    a.indicator_id,
    a.indicator_type,
    a.total_premium_percent AS result_,
    a.status_id,
    a.comment_,
    a.row_num
   FROM ( SELECT tsadv_organization_incentive_month_result_view.id,
            tsadv_organization_incentive_month_result_view.version,
            tsadv_organization_incentive_month_result_view.create_ts,
            tsadv_organization_incentive_month_result_view.created_by,
            tsadv_organization_incentive_month_result_view.update_ts,
            tsadv_organization_incentive_month_result_view.updated_by,
            tsadv_organization_incentive_month_result_view.delete_ts,
            tsadv_organization_incentive_month_result_view.deleted_by,
            tsadv_organization_incentive_month_result_view.month_result_id,
            tsadv_organization_incentive_month_result_view.company_id,
            tsadv_organization_incentive_month_result_view.period_,
            tsadv_organization_incentive_month_result_view.department_id,
            tsadv_organization_incentive_month_result_view.indicator_id,
            tsadv_organization_incentive_month_result_view.indicator_type,
            tsadv_organization_incentive_month_result_view.weight,
            tsadv_organization_incentive_month_result_view.plan_,
            tsadv_organization_incentive_month_result_view.fact,
            tsadv_organization_incentive_month_result_view.premium_percent,
            tsadv_organization_incentive_month_result_view.total_premium_percent,
            tsadv_organization_incentive_month_result_view.status_id,
            tsadv_organization_incentive_month_result_view.comment_,
            row_number() OVER (PARTITION BY tsadv_organization_incentive_month_result_view.period_, tsadv_organization_incentive_month_result_view.department_id, tsadv_organization_incentive_month_result_view.indicator_type) AS row_num
           FROM tsadv_organization_incentive_month_result_view) a
  WHERE a.row_num = 1;