alter table TSADV_BENEFICIARY add constraint FK_TSADV_BENEFICIARY_ADDRESS_KATO_CODE foreign key (ADDRESS_KATO_CODE_ID) references TSADV_DIC_KATO(ID);
create index IDX_TSADV_BENEFICIARY_ADDRESS_KATO_CODE on TSADV_BENEFICIARY (ADDRESS_KATO_CODE_ID);
