alter table TSADV_ABSENCE_REQUEST add column DISTANCE_WORKING_CONFIRM boolean ^
update TSADV_ABSENCE_REQUEST set DISTANCE_WORKING_CONFIRM = false where DISTANCE_WORKING_CONFIRM is null ;
alter table TSADV_ABSENCE_REQUEST alter column DISTANCE_WORKING_CONFIRM set not null ;
