alter table TSADV_LEARNER add constraint FK_TSADV_LEARNER_GROUP foreign key (GROUP_ID) references TSADV_LEARNER_GROUP(ID);
alter table TSADV_LEARNER add constraint FK_TSADV_LEARNER_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_LEARNER_GROUP on TSADV_LEARNER (GROUP_ID);
create index IDX_TSADV_LEARNER_PERSON_GROUP on TSADV_LEARNER (PERSON_GROUP_ID);
