alter table TSADV_LEARNING_OBJECT add constraint FK_TSADV_LEARNING_OBJECT_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_LEARNING_OBJECT_FILE on TSADV_LEARNING_OBJECT (FILE_ID);
