alter table TSADV_VIDEO_FILE_FOR_PLAY add constraint FK_TSADV_VIDEO_FILE_FOR_PLAY_SOURCE foreign key (SOURCE_ID) references SYS_FILE(ID);
alter table TSADV_VIDEO_FILE_FOR_PLAY add constraint FK_TSADV_VIDEO_FILE_FOR_PLAY_OUTPUT_FILE foreign key (OUTPUT_FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_VIDEO_FILE_FOR_PLAY_SOURCE on TSADV_VIDEO_FILE_FOR_PLAY (SOURCE_ID);
create index IDX_TSADV_VIDEO_FILE_FOR_PLAY_OUTPUT_FILE on TSADV_VIDEO_FILE_FOR_PLAY (OUTPUT_FILE_ID);
