alter table TSADV_LMS_SLIDER_IMAGE add constraint FK_TSADV_LMS_SLIDER_IMAGE_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
alter table TSADV_LMS_SLIDER_IMAGE add constraint FK_TSADV_LMS_SLIDER_IMAGE_SLIDER foreign key (SLIDER_ID) references TSADV_LMS_SLIDER(ID);
create index IDX_TSADV_LMS_SLIDER_IMAGE_IMAGE on TSADV_LMS_SLIDER_IMAGE (IMAGE_ID);
create index IDX_TSADV_LMS_SLIDER_IMAGE_SLIDER on TSADV_LMS_SLIDER_IMAGE (SLIDER_ID);
