alter table TSADV_COURSE_FEEDBACK_PERSON_ANSWER_DETAIL add column INTEGRATION_USER_LOGIN varchar(255) ;
alter table TSADV_COURSE_FEEDBACK_PERSON_ANSWER_DETAIL add column ORGANIZATION_BIN varchar(255) ;
