alter table TSADV_DIC_PROTECTION_EQUIPMENT add column INTEGRATION_USER_LOGIN varchar(255) ;
alter table TSADV_DIC_PROTECTION_EQUIPMENT add column IS_DEFAULT boolean ^
update TSADV_DIC_PROTECTION_EQUIPMENT set IS_DEFAULT = false where IS_DEFAULT is null ;
alter table TSADV_DIC_PROTECTION_EQUIPMENT alter column IS_DEFAULT set not null ;
alter table TSADV_DIC_PROTECTION_EQUIPMENT add column ORGANIZATION_BIN varchar(255) ;
