alter table TSADV_REASON_NO_PRODUCTION_CONNECTION add column INTEGRATION_USER_LOGIN varchar(255) ;
alter table TSADV_REASON_NO_PRODUCTION_CONNECTION add column IS_DEFAULT boolean ^
update TSADV_REASON_NO_PRODUCTION_CONNECTION set IS_DEFAULT = false where IS_DEFAULT is null ;
alter table TSADV_REASON_NO_PRODUCTION_CONNECTION alter column IS_DEFAULT set not null ;
alter table TSADV_REASON_NO_PRODUCTION_CONNECTION add column ORGANIZATION_BIN varchar(255) ;
