alter table TSADV_ORGANIZATION_HR_USER add constraint FK_TSADV_ORGANIZATION_HR_USER_HR_ROLE foreign key (HR_ROLE_ID) references TSADV_DIC_HR_ROLE(ID);
create index IDX_TSADV_ORGANIZATION_HR_USER_HR_ROLE on TSADV_ORGANIZATION_HR_USER (HR_ROLE_ID);
