alter table BASE_ORGANIZATION_GROUP add constraint FK_BASE_ORGANIZATION_GROUP_PAYROLL foreign key (PAYROLL_ID) references TSADV_DIC_PAYROLL(ID);
create index IDX_BASE_ORGANIZATION_GROUP_PAYROLL on BASE_ORGANIZATION_GROUP (PAYROLL_ID);
