alter table BASE_ORGANIZATION_GROUP add column ORGANIZATION_NAME_LANG1 varchar(1000) ;
alter table BASE_ORGANIZATION_GROUP add column ORGANIZATION_NAME_LANG5 varchar(1000) ;
alter table BASE_ORGANIZATION_GROUP add column ORGANIZATION_NAME_LANG3 varchar(1000) ;
alter table BASE_ORGANIZATION_GROUP add column ORGANIZATION_NAME_LANG4 varchar(1000) ;
alter table BASE_ORGANIZATION_GROUP add column ORGANIZATION_NAME_LANG2 varchar(1000) ;
alter table BASE_ORGANIZATION_GROUP add column IS_INTERNAL boolean ;
