alter table BASE_ORGANIZATION add constraint FK_BASE_ORGANIZATION_COMPANY foreign key (COMPANY_ID) references TSADV_DIC_COMPANY(ID);
create index IDX_BASE_ORGANIZATION_COMPANY on BASE_ORGANIZATION (COMPANY_ID);
