create table TSADV_MILITARY_FORM_REQUEST (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    LEGACY_ID varchar(255),
    ORGANIZATION_BIN varchar(255),
    INTEGRATION_USER_LOGIN varchar(255),
    --
    DATE_FROM date,
    DATE_TO date,
    MILITARY_DOCUMENT_TYPE_ID uuid,
    MILITARY_DOCUMENT_TYPE_NAME varchar(2000),
    UDO_ID uuid,
    DOCUMENT_NUMBER varchar(100),
    MILITARY_TYPE_ID uuid,
    MILITARY_TYPE_NAME varchar(2000),
    ATTITUDE_TO_MILITARY_ID uuid,
    TROOPS_STRUCTURE_ID uuid,
    COMPOSITION_MILITARY_REGISTRATION varchar(2000),
    MILITARY_RANK_ID uuid,
    MILITARY_RANK_NAME varchar(2000),
    OFFICER_TYPE_ID uuid,
    OFFICER_TYPE_NAME varchar(2000),
    SUITABILITY_TO_MILITARY_ID uuid,
    SPECIALIZATION varchar(255),
    ISSUE_DOC_DATE date,
    ISSUING_AUTHORITY varchar(2000),
    DELY boolean,
    DELY_DESCRIPTION varchar(255),
    REGISTER_GROUP_ID uuid,
    REGISTER_CATEGORY_ID uuid,
    DATE_POST date,
    PERSON_GROUP_ID uuid,
    REQUEST_STATUS_ID uuid,
    FILE_ID uuid,
    MILITARY_FORM_ID uuid,
    --
    primary key (ID)
);