alter table TSADV_PERSON_BENEFIT add constraint FK_TSADV_PERSON_BENEFIT_REASON foreign key (REASON_ID) references TSADV_DIC_REASON_BENIFIT(ID);
alter table TSADV_PERSON_BENEFIT add constraint FK_TSADV_PERSON_BENEFIT_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_BENEFIT_REASON on TSADV_PERSON_BENEFIT (REASON_ID);
create index IDX_TSADV_PERSON_BENEFIT_PERSON_GROUP on TSADV_PERSON_BENEFIT (PERSON_GROUP_ID);
