alter table TSADV_PERSONAL_DATA_REQUEST add column NATIONALITY_ID uuid ;
alter table TSADV_PERSONAL_DATA_REQUEST add column CITIZENSHIP_ID uuid ;
alter table TSADV_PERSONAL_DATA_REQUEST add column NATIONAL_IDENTIFIER varchar(255) ;
