alter table TSADV_ASSIGNED_GOAL add constraint FK_TSADV_ASSIGNED_GOAL_CATEGORY foreign key (CATEGORY_ID) references TSADV_DIC_GOAL_CATEGORY(ID);
create index IDX_TSADV_ASSIGNED_GOAL_CATEGORY on TSADV_ASSIGNED_GOAL (CATEGORY_ID);
