alter table TSADV_CERTIFICATE_REQUEST add constraint FK_TSADV_CERTIFICATE_REQUEST_STATUS foreign key (STATUS_ID) references TSADV_DIC_REQUEST_STATUS(ID);
create index IDX_TSADV_CERTIFICATE_REQUEST_STATUS on TSADV_CERTIFICATE_REQUEST (STATUS_ID);
