alter table TSADV_PERSON_LANGUAGE add constraint FK_TSADV_PERSON_LANGUAGE_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_PERSON_LANGUAGE add constraint FK_TSADV_PERSON_LANGUAGE_LANGUAGE foreign key (LANGUAGE_ID) references BASE_DIC_LANGUAGE(ID);
alter table TSADV_PERSON_LANGUAGE add constraint FK_TSADV_PERSON_LANGUAGE_LANGUAGE_LEVEL foreign key (LANGUAGE_LEVEL_ID) references TSADV_DIC_LANGUAGE_LEVEL(ID);
create index IDX_TSADV_PERSON_LANGUAGE_PERSON_GROUP on TSADV_PERSON_LANGUAGE (PERSON_GROUP_ID);
create index IDX_TSADV_PERSON_LANGUAGE_LANGUAGE on TSADV_PERSON_LANGUAGE (LANGUAGE_ID);
create index IDX_TSADV_PERSON_LANGUAGE_LANGUAGE_LEVEL on TSADV_PERSON_LANGUAGE (LANGUAGE_LEVEL_ID);
