alter table BASE_HIERARCHY_ELEMENT add constraint FK_BASE_HIERARCHY_ELEMENT_GROUP foreign key (GROUP_ID) references TSADV_HIERARCHY_ELEMENT_GROUP(ID);
create index IDX_BASE_HIERARCHY_ELEMENT_GROUP on BASE_HIERARCHY_ELEMENT (GROUP_ID);
