alter table TSADV_PERSON_EDUCATION add constraint FK_TSADV_PERSON_EDUCATION_FORM_STUDY foreign key (FORM_STUDY_ID) references TSADV_DIC_FORM_STUDY(ID);
create index IDX_TSADV_PERSON_EDUCATION_FORM_STUDY on TSADV_PERSON_EDUCATION (FORM_STUDY_ID);
