alter table TSADV_PERSON_BANK_DETAILS add constraint FK_TSADV_PERSON_BANK_DETAILS_BANK foreign key (BANK_ID) references BASE_BANK(ID);
alter table TSADV_PERSON_BANK_DETAILS add constraint FK_TSADV_PERSON_BANK_DETAILS_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_BANK_DETAILS_BANK on TSADV_PERSON_BANK_DETAILS (BANK_ID);
create index IDX_TSADV_PERSON_BANK_DETAILS_PERSON_GROUP on TSADV_PERSON_BANK_DETAILS (PERSON_GROUP_ID);
