alter table TSADV_VACATION_SCHEDULE add constraint FK_TSADV_VACATION_SCHEDULE_STATUS foreign key (STATUS_ID) references TSADV_ABSENCE_REQUEST_STATUS(ID);
create index IDX_TSADV_VACATION_SCHEDULE_STATUS on TSADV_VACATION_SCHEDULE (STATUS_ID);
