alter table TSADV_PERSON_HEALTH add constraint FK_TSADV_PERSON_HEALTH_PERSON_GROUP foreign key (PERSON_GROUP_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_PERSON_HEALTH_PERSON_GROUP on TSADV_PERSON_HEALTH (PERSON_GROUP_ID);
