alter table TSADV_PERSON_EXPERIENCE add constraint FK_TSADV_PERSON_EXPERIENCE_INDUSTRY foreign key (INDUSTRY_ID) references BASE_DIC_INDUSTRY(ID);
create index IDX_TSADV_PERSON_EXPERIENCE_INDUSTRY on TSADV_PERSON_EXPERIENCE (INDUSTRY_ID);
