alter table TSADV_SALARY_REQUEST add constraint FK_TSADV_SALARY_REQUEST_OLD_SALARY foreign key (OLD_SALARY_ID) references TSADV_SALARY(ID);
create index IDX_TSADV_SALARY_REQUEST_OLD_SALARY on TSADV_SALARY_REQUEST (OLD_SALARY_ID);
