alter table BASE_ASSIGNMENT add constraint FK_BASE_ASSIGNMENT_COST_CENTER foreign key (COST_CENTER_ID) references TSADV_DIC_COST_CENTER(ID);
create index IDX_BASE_ASSIGNMENT_COST_CENTER on BASE_ASSIGNMENT (COST_CENTER_ID);
