alter table TSADV_ASSIGNMENT_REQUEST add constraint FK_TSADV_ASSIGNMENT_REQUEST_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
create index IDX_TSADV_ASSIGNMENT_REQUEST_ATTACHMENT on TSADV_ASSIGNMENT_REQUEST (ATTACHMENT_ID);
