alter table BASE_POSITION_GROUP add constraint FK_BASE_POSITION_GROUP_ADMIN_APPROVE foreign key (ADMIN_APPROVE_ID) references TSADV_DIC_HR_ROLE(ID);
create index IDX_BASE_POSITION_GROUP_ADMIN_APPROVE on BASE_POSITION_GROUP (ADMIN_APPROVE_ID);
