alter table TSADV_PERSON_LEARNING_HISTORY add constraint FK_TSADV_PERSON_LEARNING_HISTORY_PARTY foreign key (PARTY_ID) references BASE_PARTY(ID);
create index IDX_TSADV_PERSON_LEARNING_HISTORY_PARTY on TSADV_PERSON_LEARNING_HISTORY (PARTY_ID);
