alter table TSADV_DISMISSAL add constraint FK_TSADV_DISMISSAL_ASSIGNMENT_GROUP foreign key (ASSIGNMENT_GROUP_ID) references BASE_ASSIGNMENT_GROUP(ID);
create index IDX_TSADV_DISMISSAL_ASSIGNMENT_GROUP on TSADV_DISMISSAL (ASSIGNMENT_GROUP_ID);
