ALTER TABLE TSADV_DIC_ABSENCE_TYPE ADD COLUMN IF NOT EXISTS ELMA_TRANSFER boolean;
update TSADV_DIC_ABSENCE_TYPE set ELMA_TRANSFER = false where ELMA_TRANSFER is null ;
alter table TSADV_DIC_ABSENCE_TYPE alter column ELMA_TRANSFER set not null ;
