alter table TSADV_RCG_FEEDBACK add constraint FK_TSADV_RCG_FEEDBACK_TYPE foreign key (TYPE_ID) references TSADV_DIC_RCG_FEEDBACK_TYPE(ID);
alter table TSADV_RCG_FEEDBACK add constraint FK_TSADV_RCG_FEEDBACK_AUTHOR foreign key (AUTHOR_ID) references BASE_PERSON_GROUP(ID);
alter table TSADV_RCG_FEEDBACK add constraint FK_TSADV_RCG_FEEDBACK_RECEIVER foreign key (RECEIVER_ID) references BASE_PERSON_GROUP(ID);
create index IDX_TSADV_RCG_FEEDBACK_TYPE on TSADV_RCG_FEEDBACK (TYPE_ID);
create index IDX_TSADV_RCG_FEEDBACK_AUTHOR on TSADV_RCG_FEEDBACK (AUTHOR_ID);
create index IDX_TSADV_RCG_FEEDBACK_RECEIVER on TSADV_RCG_FEEDBACK (RECEIVER_ID);
