alter table TSADV_TALENT_PROGRAM_STEP add constraint FK_TSADV_TALENT_PROGRAM_STEP_TALENT_PROGRAM foreign key (TALENT_PROGRAM_ID) references TSADV_TALENT_PROGRAM(ID);
alter table TSADV_TALENT_PROGRAM_STEP add constraint FK_TSADV_TALENT_PROGRAM_STEP_STEP foreign key (STEP_ID) references TSADV_DIC_TALENT_PROGRAM_STEP(ID);
alter table TSADV_TALENT_PROGRAM_STEP add constraint FK_TSADV_TALENT_PROGRAM_STEP_NOTIFICATION foreign key (NOTIFICATION_ID) references BASE_NOTIFICATION_TEMPLATE(ID);
drop index if exists IDX_TSADV_TALENT_PROGRAM_STEP_UK_STEP_ID;
create unique index if not exists IDX_TSADV_TALENT_PROGRAM_STEP_UK_STEP_ID on TSADV_TALENT_PROGRAM_STEP (TALENT_PROGRAM_ID,STEP_ID) where DELETE_TS is null ;
drop index if exists IDX_TSADV_TALENT_PROGRAM_STEP_UK_ORDER_NUM;
create index if not exists IDX_TSADV_TALENT_PROGRAM_STEP_TALENT_PROGRAM on TSADV_TALENT_PROGRAM_STEP (TALENT_PROGRAM_ID);
create index if not exists IDX_TSADV_TALENT_PROGRAM_STEP_STEP on TSADV_TALENT_PROGRAM_STEP (STEP_ID);
create index if not exists IDX_TSADV_TALENT_PROGRAM_STEP_NOTIFICATION on TSADV_TALENT_PROGRAM_STEP (NOTIFICATION_ID);
