alter table TSADV_IMPORT_HISTORY add constraint FK_TSADV_IMPORT_HISTORY_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table TSADV_IMPORT_HISTORY add constraint FK_TSADV_IMPORT_HISTORY_IMPORT_SCENARIO foreign key (IMPORT_SCENARIO_ID) references TSADV_IMPORT_SCENARIO(ID);
create index IDX_TSADV_IMPORT_HISTORY_FILE on TSADV_IMPORT_HISTORY (FILE_ID);
create index IDX_TSADV_IMPORT_HISTORY_IMPORT_SCENARIO on TSADV_IMPORT_HISTORY (IMPORT_SCENARIO_ID);
