alter table TSADV_IMPORT_HISTORY_LOG add constraint FK_TSADV_IMPORT_HISTORY_LOG_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_TSADV_IMPORT_HISTORY_LOG_FILE on TSADV_IMPORT_HISTORY_LOG (FILE_ID);
